services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mokkoji-mysql
    ports:
      - '${MYSQL_PORT}:3306'
    restart: always

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mokkoji-mysql
    command: --default-authentication-plugin=mysql_native_password



