services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mokkoji-mysql
    ports:
      - '${MYSQL_PORT}:3306'
    restart: always

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mokkoji-mysql
    command: --default-authentication-plugin=mysql_native_password

  # Redis
  redis:
    image: redis:7.2.5
    container_name: mokkoji-redis
    ports:
      - '6379:6379'


  # MongoDB
  mongodb:
    image: mongo:6.0.16
    container_name: mokkoji-mongodb
    ports:
      - '37017:27017'
    volumes:
      - ./mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}


