services:
  spring:
    image: hwangjiyoung/server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: mokkoji-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - mokkoji-net

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mokkoji-mysql
    ports:
      - '3306:3306'
    restart: always

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mokkoji-net

  # Redis
  redis:
    image: redis:7.2.5
    container_name: mokkoji-redis
    ports:
      - '6379:6379'
    networks:
      - mokkoji-net


networks:
  mokkoji-net:
